### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [nathanclevenger/ai-functions#1]
- [ ] Develop Initial Function Experiments
- [ ] Define Experimental Function Abstraction
- [ ] Explore Simplified Schema Definition
- [ ] Support Recursive Functions
- [ ] Support Inverse Functions
- [ ] Support Javascript Sandbox
- [ ] Support Javascript Events
- [ ] Support Webhook Callbacks
- [ ] Support Queue & PubSub Architectures
